logging:
  level:
    root: INFO
#  file:
#    name: gameSession.log

gameplay:
  config:
    5:
      - 2
      - 2
      - 3
      - 2
      - 3
      - 3
    6:
      - 2
      - 2
      - 3
      - 4
      - 3
      - 4
    7:
      - 3
      - 2
      - 3
      - 3
      - 4
      - 4
    8:
      - 3
      - 3
      - 4
      - 4
      - 5
      - 5
    9:
      - 3
      - 3
      - 4
      - 4
      - 5
      - 5
    10:
      - 4
      - 3
      - 4
      - 4
      - 5
      - 5
  gameIdRank : 100_000
